version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/password"

  python-app:
    image: python:3.8-slim
    container_name: python-app
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: bash -c "pip install -r requirements.txt && python main.py"
    depends_on:
      - mongodb
      - neo4j

volumes:
  mongo-data: